### ISSUE TITLE
Font-Stack

### ISSUE THREAD

**Issue by devin2712** [jonathanyax/webscienceproject#3]
## Font Issues
* OnPoint font doesn't look sharp. Something to look into?
* Need to incorporate a font-stack and eliminate duplicated font-stack statements in CSS.

**Comment by errskipower** [comment]
I added a text-shadow to a lot of the OnPoint font text because Doris said it looked too thin.

**Comment by devin2712** [comment]
Gotcha. 

As a temporary solution, I've added -webkit-text-stroke which addresses this issue for most browsers. If I'm not mistaken, the text-shadow property is adding a slight 1/2px blur and isn't doing exactly what we want.

**Comment by errskipower** [comment]
The text-stroke is essentially the same as making the font-weight bold.  I tested it and both look the same.  From a typography standpoint, and maybe Doris can chime in, a false-bold is a no-no if a specific font does not come with a bold style.  We should all discuss this today and decide the best route to take.

**Comment by devin2712** [comment]
![screen shot 2015-03-11 at 1 24 53 pm](https://cloud.githubusercontent.com/assets/1658227/6602432/09619ac8-c7f2-11e4-8b35-cae172c130fd.png)

**Left** : Just <code>text-shadow: 0 0 2px #8B9DA8;</code>.
**Right** : Additional line <code>-webkit-text-stroke: 2px #8B9DA8;</code>

text-shadow's third parameter is a blur-radius so I don't think that's doing anything beyond making the font fuzzy

The text-stroke is likely supported by Chrome/Safari but beyond that, I'm not sure.

<code>font-weight: bold;</code> is likely set to look for a bold font in the specified font-family, which doesn't exist for us, so if we added a <code>font-weight: bold</code> line, it obviously wouldn't change anything.  <code>text-stroke</code>, however, does have an impact on some browsers.

**Comment by devin2712** [comment]
As for the typographic no-no you've mentioned, this is precisely the intention of adding the text-shadow, no?

**Comment by errskipower** [comment]
What I meant was doing text-stroke and font-weight: bold, look exactly the
same when I tested them (so font-weight: bold does change the look of the
font and would be a more browser compatible solution than text-stroke since
they look the same).  Since our font-family does not contain a bold font,
it's making a false bold.  I understand that the text-shadow looks bad and
I'm not saying we should use it, but we should consider the ramifications
of doing text-stroke/font-weight bold.
