### ISSUE TITLE
Mobile region nav design thoughts

### ISSUE THREAD

**Issue by devin2712** [jonathanyax/webscienceproject#4]
![screen shot 2015-03-11 at 1 13 33 pm](https://cloud.githubusercontent.com/assets/1658227/6602187/78c2290c-c7f0-11e4-9b68-8527a0fd0849.png)

# Mobile Design Question
I believe Doris envisioned the gray bar to iteratively change to green in chunks as the cities changed.  Currently, it is border-bottom solution, which is cool.  Only concern is that on mobile, as seen in the screenshot, is that with border-bottom, the page shifts as you hover in the nav.

**Comment by errskipower** [comment]
All that needs to be done to fix the page shift is to adjust padding/margin so I'll fix that now. I'm confused as to what grey bar you're talking about haha
