### ISSUE TITLE
Convert icons to onPoint font

### ISSUE THREAD

**Issue by devin2712** [jonathanyax/webscienceproject#5]

**Comment by errskipower** [comment]
The lock icon is missing from the icons reference so I'm assuming it's missing from the font files?

**Comment by dorisxian** [comment]
Yep, some icons are still missing from the font file and i will do a update later. Also, i couldn't get the logo icon in the correct position.

**Comment by errskipower** [comment]
I just pushed a commit to fix the logo icon positioning before seeing this haha
