### ISSUE TITLE
Notes on Jade conversion

### ISSUE THREAD

**Issue by devin2712** [jonathanyax/webscienceproject#6]
I had to make some changes to the main stylesheet and index.html module, so I'm not sure if that would affect the tentative Jade template.  We had some bugs in the rendering of the onPoint font on smaller widths and there was a stray font awesome user profile icon which messed with the overall line-height and stuff.

I think we're on the final homepage mockup now... just wanted to check in and notify you in case you've gone and packaged homepage for Jade rendering!

**Comment by errskipower** [comment]
I actually finished the mobile view of the Jade homepage last night, but I'll view the diff and adjust it with your changes.
